#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# NSO pgBouncer Setup — Connection pooling for multi-node
#
# Usage: bash nso/base/setup-pgbouncer.sh
#
# Installs pgBouncer in transaction pooling mode between
# gateway nodes and PostgreSQL. Allows 200+ effective
# connections with only 50 real PostgreSQL connections.
# ─────────────────────────────────────────────────────────

set -euo pipefail

LOG_TAG="[nso:pgbouncer]"
log()  { echo "$LOG_TAG $*"; }
die()  { echo "$LOG_TAG ERROR: $*" >&2; exit 1; }

# ── Config ──
PGBOUNCER_PORT=${PGBOUNCER_PORT:-6432}
PGBOUNCER_MAX_CLIENT_CONN=${PGBOUNCER_MAX_CLIENT_CONN:-200}
PGBOUNCER_DEFAULT_POOL_SIZE=${PGBOUNCER_DEFAULT_POOL_SIZE:-20}
PGBOUNCER_MIN_POOL_SIZE=${PGBOUNCER_MIN_POOL_SIZE:-5}
PGBOUNCER_RESERVE_POOL=${PGBOUNCER_RESERVE_POOL:-5}
DB_PASSWORD=${DB_PASSWORD:-$(grep 'DB_PASSWORD' /opt/nso/config/nso.env 2>/dev/null | cut -d= -f2 || echo "nso")}
DB_NAME=${DB_NAME:-nso}
DB_USER=${DB_USER:-nso}

# ── Install ──
log "Installing pgBouncer..."
apt-get update -qq
apt-get install -y -qq pgbouncer > /dev/null 2>&1
log "pgBouncer installed"

# ── Configure ──
log "Configuring pgBouncer (port=$PGBOUNCER_PORT, max_clients=$PGBOUNCER_MAX_CLIENT_CONN, pool=$PGBOUNCER_DEFAULT_POOL_SIZE)..."

cat > /etc/pgbouncer/pgbouncer.ini <<EOF
;; NSO pgBouncer configuration
;; Generated by setup-pgbouncer.sh

[databases]
${DB_NAME} = host=127.0.0.1 port=5432 dbname=${DB_NAME}

;; Allow gateway nodes to connect for user managed databases
* = host=127.0.0.1 port=5432

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = ${PGBOUNCER_PORT}
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

;; Transaction pooling: connections returned after each transaction
;; This is the key setting that enables 200+ effective connections
pool_mode = transaction

;; Pool sizing
max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN}
default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE}
min_pool_size = ${PGBOUNCER_MIN_POOL_SIZE}
reserve_pool_size = ${PGBOUNCER_RESERVE_POOL}
reserve_pool_timeout = 5

;; Timeouts
server_connect_timeout = 15
server_login_retry = 1
client_login_timeout = 60
server_idle_timeout = 600
query_timeout = 300
query_wait_timeout = 120
client_idle_timeout = 0

;; Logging
log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
stats_period = 60

;; Admin
admin_users = ${DB_USER}
stats_users = ${DB_USER}

;; Security
server_tls_sslmode = disable
EOF

# ── Auth file ──
# Generate MD5 password hash for pgBouncer
MD5_PASS=$(echo -n "${DB_PASSWORD}${DB_USER}" | md5sum | cut -d' ' -f1)
cat > /etc/pgbouncer/userlist.txt <<EOF
"${DB_USER}" "md5${MD5_PASS}"
EOF
chmod 640 /etc/pgbouncer/userlist.txt
chown pgbouncer:pgbouncer /etc/pgbouncer/userlist.txt

# ── Systemd ──
log "Enabling pgBouncer service..."
systemctl enable pgbouncer
systemctl restart pgbouncer

# ── Verify ──
sleep 2
if systemctl is-active --quiet pgbouncer; then
    log "pgBouncer running on port $PGBOUNCER_PORT"
    log "Connection string: postgresql://${DB_USER}:***@localhost:${PGBOUNCER_PORT}/${DB_NAME}"
    log ""
    log "To use pgBouncer, update DATABASE_URL in /opt/nso/config/nso.env:"
    log "  DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:${PGBOUNCER_PORT}/${DB_NAME}"
    log ""
    log "Pool stats: psql -p ${PGBOUNCER_PORT} -U ${DB_USER} pgbouncer -c 'SHOW POOLS;'"
else
    die "pgBouncer failed to start — check: journalctl -u pgbouncer -n 20"
fi

log "Done."
