#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# NSO Redis Setup — Distributed state for multi-node clusters
#
# Usage: bash nso/base/setup-redis.sh [--password <pass>]
#
# Installs Redis for:
# - Leader election (reconciler, monitors)
# - Rate limiting (distributed sliding window)
# - LB round-robin counters
# - Pub/Sub for cross-node events
# - Cluster heartbeats
# ─────────────────────────────────────────────────────────

set -euo pipefail

LOG_TAG="[nso:redis]"
log()  { echo "$LOG_TAG $*"; }
die()  { echo "$LOG_TAG ERROR: $*" >&2; exit 1; }

# Parse args
REDIS_PASSWORD=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --password) REDIS_PASSWORD="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# Auto-generate password if not provided
if [[ -z "$REDIS_PASSWORD" ]]; then
    REDIS_PASSWORD=$(openssl rand -hex 32)
    log "Generated Redis password (first 8 chars): ${REDIS_PASSWORD:0:8}..."
fi

# ── Install ──
log "Installing Redis..."
apt-get update -qq
apt-get install -y -qq redis-server > /dev/null 2>&1
log "Redis installed"

# ── Configure ──
log "Configuring Redis..."

cat > /etc/redis/redis.conf <<EOF
# NSO Redis configuration
# Generated by setup-redis.sh

# Network
bind 0.0.0.0
port 6379
protected-mode yes
requirepass ${REDIS_PASSWORD}

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Persistence (RDB snapshots every 5 min if 100+ keys changed)
save 300 100
dbfilename nso-redis.rdb
dir /var/lib/redis

# Logging
loglevel notice
logfile /var/log/redis/redis-server.log

# Performance
tcp-backlog 511
timeout 300
tcp-keepalive 60

# Security
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command DEBUG ""
EOF

# ── Systemd ──
log "Enabling Redis service..."
systemctl enable redis-server
systemctl restart redis-server

# ── Verify ──
sleep 2
if redis-cli -a "$REDIS_PASSWORD" ping 2>/dev/null | grep -q PONG; then
    log "Redis running on port 6379"
    REDIS_URL="redis://:${REDIS_PASSWORD}@localhost:6379/0"
    log ""
    log "Add to /opt/nso/config/nso.env:"
    log "  REDIS_URL=${REDIS_URL}"
    log ""

    # Append to nso.env if it exists
    ENV_FILE="/opt/nso/config/nso.env"
    if [[ -f "$ENV_FILE" ]]; then
        if ! grep -q "REDIS_URL" "$ENV_FILE"; then
            echo "REDIS_URL=${REDIS_URL}" >> "$ENV_FILE"
            log "REDIS_URL appended to $ENV_FILE"
        else
            log "REDIS_URL already in $ENV_FILE — not overwriting"
        fi
    fi
else
    die "Redis failed to start — check: journalctl -u redis-server -n 20"
fi

log "Done."
